// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2qposTW7S1fNW224cmmZGHbfwA2mkT4',
    appId: '1:334252914139:web:4025f9e8b9abb1eeae63fe',
    messagingSenderId: '334252914139',
    projectId: 'fir-authentication-7d8b1',
    authDomain: 'fir-authentication-7d8b1.firebaseapp.com',
    storageBucket: 'fir-authentication-7d8b1.appspot.com',
    measurementId: 'G-KLBF0481PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBpKPgXd1IDPkYPQQxkohcHdw6fI6YrI',
    appId: '1:334252914139:android:51fd9e9a8010e268ae63fe',
    messagingSenderId: '334252914139',
    projectId: 'fir-authentication-7d8b1',
    storageBucket: 'fir-authentication-7d8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQqONOB6JkxTfquud6Ajl8ImzJpBESXxg',
    appId: '1:334252914139:ios:96bce30b69dc07b6ae63fe',
    messagingSenderId: '334252914139',
    projectId: 'fir-authentication-7d8b1',
    storageBucket: 'fir-authentication-7d8b1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQqONOB6JkxTfquud6Ajl8ImzJpBESXxg',
    appId: '1:334252914139:ios:96bce30b69dc07b6ae63fe',
    messagingSenderId: '334252914139',
    projectId: 'fir-authentication-7d8b1',
    storageBucket: 'fir-authentication-7d8b1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2qposTW7S1fNW224cmmZGHbfwA2mkT4',
    appId: '1:334252914139:web:ee66dc025d7d3ff4ae63fe',
    messagingSenderId: '334252914139',
    projectId: 'fir-authentication-7d8b1',
    authDomain: 'fir-authentication-7d8b1.firebaseapp.com',
    storageBucket: 'fir-authentication-7d8b1.appspot.com',
    measurementId: 'G-J93DS46E45',
  );
}
